# Generated by Django 4.2.3 on 2023-09-25 11:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Products.category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('garanty', models.CharField(help_text='شرایط گارانتی', max_length=50)),
                ('persianName', models.CharField(help_text='نام فارسی محصول', max_length=50)),
                ('price', models.IntegerField(help_text='قیمت محصول')),
                ('englishName', models.CharField(help_text='نام انگلیسی محصول', max_length=50)),
                ('desc', models.TextField(help_text='توضیحات محصول', max_length=2000)),
                ('original', models.BooleanField(default=False)),
                ('deliveryType', models.IntegerField(choices=[[0, 'تحویل با پست']], help_text='نوع تحویل محصول')),
                ('offerPrice', models.IntegerField(default=0, help_text='میزان تخفیف محصول (صفر به معنای بدون تخفیف)')),
                ('countCanBuy', models.PositiveIntegerField(default=0, help_text='هر کاربر به چه تعداد از این محصول می تواند بخرد؟ (صفر به معنای آزاد)')),
                ('category', models.ForeignKey(help_text='دسته بندی', on_delete=django.db.models.deletion.CASCADE, to='Products.category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProdutData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='نام ویژگی محصول', max_length=50)),
                ('amount', models.CharField(help_text='مقدار ویژگی محصول', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(help_text='آدرس سرور ارائه دهنده عکس', max_length=50)),
                ('product', models.ForeignKey(help_text='این عکس مربوط به کدام محصول است؟', on_delete=django.db.models.deletion.CASCADE, to='Products.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='data',
            field=models.ManyToManyField(to='Products.produtdata'),
        ),
        migrations.CreateModel(
            name='KeeperCountItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='نام ویژگی محصول', max_length=50)),
                ('amount', models.IntegerField(help_text='مقدار ویژگی محصول')),
                ('product', models.ForeignKey(help_text='محصولی که این مقدار برای آن است.', on_delete=django.db.models.deletion.CASCADE, to='Products.product')),
            ],
        ),
    ]
