# Generated by Django 4.2.3 on 2023-10-07 11:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('done', models.SmallIntegerField(choices=[[-1, 'پرداخت نشده'], [0, 'در حال بررسی سفارش'], [1, 'در حال آماده سازی'], [2, 'ارسال شده'], [3, 'سفارش انجام شده']], default=0)),
                ('price', models.IntegerField()),
                ('count', models.IntegerField()),
                ('postCode', models.IntegerField(blank=True, help_text='شماره پیگیری از اداره پست', null=True)),
                ('transactionAuthCode', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('count', models.PositiveIntegerField()),
                ('price', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.product')),
                ('select', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.keepercountitem')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
