# Generated by Django 4.2.3 on 2023-10-07 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='postCode',
            field=models.CharField(blank=True, help_text='شماره پیگیری از اداره پست', max_length=50, null=True),
        ),
    ]
