# Generated by Django 4.2.3 on 2023-08-14 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Core', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoffeeOrder',
            fields=[
                ('reservemainmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Core.reservemainmodel')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
            bases=('Core.reservemainmodel',),
        ),
    ]
