# Generated by Django 4.2.3 on 2023-08-14 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Caffeh', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffeeorder',
            name='desc',
            field=models.TextField(default='', max_length=40000),
        ),
    ]
